### ISSUE TITLE
Datas and pictures not showing

### ISSUE THREAD

**Issue by lagoo178** [h01d/ChatApp#6]
I've tried debugging your chatapp but using my firebase database and converted it to androidx. but i run into an issue. Datas and picture are not showing in the app, but it's stored in the database. What's the solution? (code hadn't been touch, except for few imports due to androidx conversion)

Thanks, you've made a solid app btw.

**Comment by iamraf** [comment]
I can't know without debugging the code. Make sure your configuration is setup properly, as well as, firebase is returning the data.

**Comment by lagoo178** [comment]
I've checked the app's build gradle and see nothing wrong, the app has no error shown in the log but things like fragments and pictures didn't show any data from firebase. 
you can see from the image below, fragment chat is blank, but not empty. my data seems to be not showing from the database
![image](https://user-images.githubusercontent.com/33061081/84282589-24c21580-ab64-11ea-8930-7efd6d4c4059.png) 

empty request fragment
![image](https://user-images.githubusercontent.com/33061081/84282643-32779b00-ab64-11ea-8a4c-f676f5729ba3.png)

**Comment by iamraf** [comment]
After a half an hour refactoring, i have managed to build and run it. It seems to be working fine on me.

**Comment by lagoo178** [comment]
Do you have discord accounts or any in particular? for giving you further details regarding my problem.

**Comment by iamraf** [comment]
You can email me @ rafaellos.g9@gmail.com
